name: Build and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write


jobs:
  run-unit-tests:
    uses: ./.github/workflows/run-unit-test.yml

  run-e2e-tests:
    uses: ./.github/workflows/run-e2e-test.yml

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [run-unit-tests, run-e2e-tests]

    environment:
      name: ${{ github.ref_name == 'main' && 'main' || 'dev' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_AR_REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.GCP_AR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_AR_REPOSITORY }}/${{ secrets.GCP_AR_IMAGE }}:${{ github.sha }} \
            -t ${{ secrets.GCP_AR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_AR_REPOSITORY }}/${{ secrets.GCP_AR_IMAGE }}:latest \
            .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.GCP_AR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_AR_REPOSITORY }}/${{ secrets.GCP_AR_IMAGE }}:${{ github.sha }}
          docker push ${{ secrets.GCP_AR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_AR_REPOSITORY }}/${{ secrets.GCP_AR_IMAGE }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_AR_IMAGE }} \
            --image=${{ secrets.GCP_AR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_AR_REPOSITORY }}/${{ secrets.GCP_AR_IMAGE }}:${{ github.sha }} \
            --region=${{ secrets.GCP_AR_REGION }} \
            --project=${{ secrets.GCP_PROJECT_ID }}
